config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :castrations
  resources :posters
  resources :gatos
  root 'gatos#index'

  resources :users

end

app/models/castration.rb
class Castration < ActiveRecord::Base
  has_many :gatos
end

app/controllers/castrations_controller.rb
class CastrationsController < ApplicationController
  before_action :set_castration, only: [:show, :edit, :update, :destroy]

  # GET /castrations
  # GET /castrations.json
  def index
    @castrations = Castration.all
  end

  # GET /castrations/1
  # GET /castrations/1.json
  def show
  end

  # GET /castrations/new
  def new
    @castration = Castration.new
  end

  # GET /castrations/1/edit
  def edit
  end

  # POST /castrations
  # POST /castrations.json
  def create
    @castration = Castration.new(castration_params)

    respond_to do |format|
      if @castration.save
        format.html { redirect_to @castration, notice: 'Castration was successfully created.' }
        format.json { render :show, status: :created, location: @castration }
      else
        format.html { render :new }
        format.json { render json: @castration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /castrations/1
  # PATCH/PUT /castrations/1.json
  def update
    respond_to do |format|
      if @castration.update(castration_params)
        format.html { redirect_to @castration, notice: 'Castration was successfully updated.' }
        format.json { render :show, status: :ok, location: @castration }
      else
        format.html { render :edit }
        format.json { render json: @castration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /castrations/1
  # DELETE /castrations/1.json
  def destroy
    @castration.destroy
    respond_to do |format|
      format.html { redirect_to castrations_url, notice: 'Castration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_castration
      @castration = Castration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def castration_params
      params.require(:castration).permit(:place, :price, :when)
    end
end

app/helpers/castrations_helper.rb
module CastrationsHelper
end

app/views/castrations/_form.html.erb
<%= form_for(@castration) do |f| %>
  <% if @castration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@castration.errors.count, "error") %> prohibited this castration from being saved:</h2>

      <ul>
      <% @castration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :when %><br>
    <%= f.date_select :when %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/castrations/edit.html.erb
<h1>Editing Castration</h1>

<%= render 'form' %>

<%= link_to 'Show', @castration %> |
<%= link_to 'Back', castrations_path %>

app/views/castrations/index.html.erb
<h1>Listing Castrations</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Price</th>
      <th>When</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @castrations.each do |castration| %>
      <tr>
        <td><%= castration.place %></td>
        <td><%= castration.price %></td>
        <td><%= castration.when %></td>
        <td><%= link_to 'Show', castration %></td>
        <td><%= link_to 'Edit', edit_castration_path(castration) %></td>
        <td><%= link_to 'Destroy', castration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Castration', new_castration_path %>

app/views/castrations/new.html.erb
<h1>New Castration</h1>

<%= render 'form' %>

<%= link_to 'Back', castrations_path %>

app/views/castrations/show.html.erb
<p>
  <strong>Place:</strong>
  <%= @castration.place %>
</p>

<p>
  <strong>Price:</strong>
  <%= @castration.price %>
</p>

<p>
  <strong>When:</strong>
  <%= @castration.when %>
</p>

<%= link_to 'Edit', edit_castration_path(@castration) %> |
<%= link_to 'Back', castrations_path %>