config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :castrations
  resources :posters
  resources :gatos
  root 'gatos#index'

  resources :users

end

app/models/poster.rb
class Poster < ActiveRecord::Base
  belongs_to :user
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  before_action :authenticate_user!, except:[:show, :index]
  before_action :set_poster, only: [:show, :edit, :update, :destroy]

  # GET /posters
  # GET /posters.json
  def index
    @posters = Poster.all
  end

  # GET /posters/1
  # GET /posters/1.json
  def show
  end

  # GET /posters/new
  def new
    @poster = Poster.new
  end

  # GET /posters/1/edit
  def edit
  end

  # POST /posters
  # POST /posters.json
  def create
    @poster = Poster.new(poster_params)
    @poster.user_id = current_user.id

    respond_to do |format|
      if @poster.save
        format.html { redirect_to @poster, notice: 'Poster was successfully created.' }
        format.json { render :show, status: :created, location: @poster }
      else
        format.html { render :new }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posters/1
  # PATCH/PUT /posters/1.json
  def update
    respond_to do |format|
      if @poster.update(poster_params)
        format.html { redirect_to @poster, notice: 'Poster was successfully updated.' }
        format.json { render :show, status: :ok, location: @poster }
      else
        format.html { render :edit }
        format.json { render json: @poster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posters/1
  # DELETE /posters/1.json
  def destroy
    @poster.destroy
    respond_to do |format|
      format.html { redirect_to posters_url, notice: 'Poster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poster
      @poster = Poster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poster_params
      params.require(:poster).permit(:tipo, :description, :user_id)
    end
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/views/posters/_form.html.erb
<%= form_for(@poster) do |f| %>
  <% if @poster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poster.errors.count, "error") %> prohibited this poster from being saved:</h2>

      <ul>
      <% @poster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posters/edit.html.erb
<h1>Editing Poster</h1>

<%= render 'form' %>

<%= link_to 'Show', @poster %> |
<%= link_to 'Back', posters_path %>

app/views/posters/index.html.erb
<h1>Listing Posters</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posters.each do |poster| %>
      <tr>
        <td><%= poster.tipo %></td>
        <td><%= poster.description %></td>
        <td><%= link_to 'Show', poster %></td>
        <td><%= link_to 'Edit', edit_poster_path(poster) %></td>
        <td><%= link_to 'Destroy', poster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poster', new_poster_path %>

app/views/posters/new.html.erb
<h1>New Poster</h1>

<%= render 'form' %>

<%= link_to 'Back', posters_path %>

app/views/posters/show.html.erb
<p>
  <strong>Tipo:</strong>
  <%= @poster.tipo %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @poster.description %>
</p>

<%= link_to 'Edit', edit_poster_path(@poster) %> |
<%= link_to 'Back', posters_path %>